//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSBApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProdOrdInfo
    {
        public long productionId { get; set; }
        public string status { get; set; }
        public int statusId { get; set; }
        public string productNumber { get; set; }
        public string description { get; set; }
        public int quantity { get; set; }
        public string workstationId { get; set; }
        public string workCell { get; set; }
        public Nullable<int> numberEmployees { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<int> duration { get; set; }
        public int stadardAsyTime { get; set; }
    }
}
